### PR TITLE
DO NOT USE PULL REQUESTS; SYMFONY 1 IS NOT MAINTAINED ANYMORE.

### PR DESCRIPTION
**Pull request by fabpot**

### CODE REVIEW

**Comment by cystbear** [comment]
http://trac.symfony-project.org

**Comment by garak** [comment]
Looks like opening new tickets isn't allowed anymore, http://trac.symfony-project.org/newticket says "TICKET_CREATE privileges are required to perform this operation" :-(

**Comment by ducin** [comment]
Yep, I confirm: after logging in, adding new tickets is not possible due to the lack of privileges.

Edit: Unfortunately, actual symfony1.4 tests fail on travis: https://travis-ci.org/tkoomzaaskz/symfony1/jobs/5419417. It'd be nice if we had the possibility to create tickets/pull requests anywhere.

**Comment by andreikainer** [comment]
Hi, the Symfony 1 API `http://www.symfony-project.org/api/` server seems to be down since last week. Any chance we can have this back live? 

Or alternatively, where am I able to find the API docs hosted elsewhere? Thank you!

**Comment by digitalbase** [comment]
I think this project deserves a mention here -> https://github.com/LExpress/symfony1

**Pull request closed without merging**
